In [1]:
import requests
import pandas as pd

In [2]:
tablas_ine = ['2076','46298']

In [3]:
# O el parámetro que la API requiera
params = { "limit": 3 }

In [4]:
def extract_data(tabla_to_extract):
    # Realizar la solicitud GET
    response = requests.get(f"https://servicios.ine.es/wstempus/jsCache/es/DATOS_TABLA/{tabla_to_extract}?tip=AM&", params=params)

    # Verificar si la solicitud fue exitosa
    if response.status_code == 200:
        try:
            # Parsear los datos JSON
            data = response.json()
            # Convertir los datos a un DataFrame
            df = pd.DataFrame(data)
        except ValueError as e:
            # Manejar errores de parsing de JSON
            print(f"Error al parsear JSON: {e}")
            df = pd.DataFrame()  # Retornar un DataFrame vacío
    else:
        # Manejar el error de solicitud
        print(f"Error en la solicitud: {response.status_code}")
        print(response.text)
        df = pd.DataFrame()  # Retornar un DataFrame vacío

    return df.head()

In [6]:
#pip install openpyxl

In [7]:
#configurar pandas para mostrar el contenido completo
pd.set_option('display.max_colwidth', None)  #sin límite de ancho de columna
pd.set_option('display.max_rows', None)      #mostrar todas las filas
pd.set_option('display.max_columns', None)   #mostrar todas las columnas

In [17]:
for tabla_to_extract in tablas_ine:
    df = extract_data(tabla_to_extract)
    if not df.empty:
        # df_transform = transform(df)
        # Guardar como archivo Excel usando to_excel
        df.head().to_excel(f'C:/Users/dcastells/Desktop/MI_PATH/projects_sql_python/data/landing_zone/{tabla_to_extract}.xlsx', index=False)
        # Insertar en SQL Server
        df.to_sql(tabla_to_extract, engine, if_exists="replace", index=False)
        print(f"La tabla {tabla_to_extract} fue procesada")

La tabla 2076 fue procesada
La tabla 46298 fue procesada

In [36]:
import pandas as pd
import json

def explode_columnas(df):
    rows = []
    
    for _, row in df.iterrows():
        # Convertir las columnas MetaData y Data en diccionarios si no lo son
        meta_data = json.loads(row['MetaData']) if isinstance(row['MetaData'], str) else row['MetaData']
        data = json.loads(row['Data']) if isinstance(row['Data'], str) else row['Data']
        
        # Crear filas para cada clave-valor de MetaData
        if isinstance(meta_data, dict):
            for key, value in meta_data.items():
                rows.append({
                    'COD': row['COD'],
                    'Nombre': row['Nombre'],
                    'Tipo': 'MetaData',
                    'Clave': key,
                    'Valor': value
                })
        
        # Crear filas para cada clave-valor de Data
        if isinstance(data, dict):
            for key, value in data.items():
                rows.append({
                    'COD': row['COD'],
                    'Nombre': row['Nombre'],
                    'Tipo': 'Data',
                    'Clave': key,
                    'Valor': value
                })
    
    # Convertir las filas generadas en un nuevo DataFrame
    exploded_df = pd.DataFrame(rows)
    return exploded_df

# Ejemplo de uso:
# df = pd.read_csv("ruta_del_archivo.csv")  # O el DataFrame que ya tienes cargado
df_exploded = explode_columnas(df)
# print(df_exploded)

In [38]:
import pandas as pd
import json

def desglosar_meta_y_data(df):
    rows = []
    
    for _, row in df.iterrows():
        # Procesar Meta_Valor si no es None
        if row['Meta_Valor'] is not None:
            meta_value = json.loads(row['Meta_Valor']) if isinstance(row['Meta_Valor'], str) else row['Meta_Valor']
            for key, value in meta_value.items():
                rows.append({
                    'COD': row['COD'],
                    'Nombre': row['Nombre'],
                    'Tipo': row['Tipo'],
                    'Clave': row['Clave'],
                    'SubClave': key,
                    'SubValor': value
                })
        
        # Procesar Data_Valor si no es None
        if row['Data_Valor'] is not None:
            data_value = json.loads(row['Data_Valor']) if isinstance(row['Data_Valor'], str) else row['Data_Valor']
            for key, value in data_value.items():
                rows.append({
                    'COD': row['COD'],
                    'Nombre': row['Nombre'],
                    'Tipo': row['Tipo'],
                    'Clave': row['Clave'],
                    'SubClave': key,
                    'SubValor': value
                })
    
    # Crear un DataFrame con las filas desglosadas
    desglosado_df = pd.DataFrame(rows)
    return desglosado_df

# Ejemplo de uso:
# df = pd.read_csv("ruta_del_archivo.csv")  # O el DataFrame que ya tienes cargado
df_desglosado = desglosar_meta_y_data(df_desglosado)
# print(df_desglosado)
df_desglosado

,COD,Nombre,Tipo,Clave,SubClave,SubValor
0,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,MetaData,Item_0,Id,571
1,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,MetaData,Item_0,T3_Variable,PUNTOS TURISTÍCOS
2,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,MetaData,Item_0,Nombre,Vitoria-Gasteiz
3,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,MetaData,Item_0,Codigo,01059
4,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,MetaData,Item_1,Id,284338
5,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,MetaData,Item_1,T3_Variable,Concepto turístico
6,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,MetaData,Item_1,Nombre,Tarifa media diaria (ADR)
7,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,MetaData,Item_1,Codigo,F
8,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,MetaData,Item_2,Id,9834
9,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,MetaData,Item_2,T3_Variable,TIPO DE CATEGORIA
10,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,MetaData,Item_2,Nombre,Total categorías
11,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,MetaData,Item_2,Codigo,
12,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,MetaData,Item_3,Id,72
13,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,MetaData,Item_3,T3_Variable,Tipo de dato
14,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,MetaData,Item_3,Nombre,Dato
15,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,MetaData,Item_3,Codigo,0
16,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_0,Fecha,2024-12-01T00:00:00.000+01:00
17,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_0,T3_TipoDato,Provisional
18,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_0,T3_Periodo,M12
19,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_0,Anyo,2024
20,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_0,Valor,65.49
21,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_1,Fecha,2024-11-01T00:00:00.000+01:00
22,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_1,T3_TipoDato,Provisional
23,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_1,T3_Periodo,M11
24,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_1,Anyo,2024
25,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_1,Valor,64.87
26,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_2,Fecha,2024-10-01T00:00:00.000+02:00
27,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_2,T3_TipoDato,Provisional
28,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_2,T3_Periodo,M10
29,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_2,Anyo,2024
30,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_2,Valor,66.39
31,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_3,Fecha,2024-09-01T00:00:00.000+02:00
32,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_3,T3_TipoDato,Provisional
33,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_3,T3_Periodo,M09
34,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_3,Anyo,2024
35,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_3,Valor,71.79
36,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_4,Fecha,2024-08-01T00:00:00.000+02:00
37,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_4,T3_TipoDato,Provisional
38,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_4,T3_Periodo,M08
39,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_4,Anyo,2024
40,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_4,Valor,83.75
41,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_5,Fecha,2024-07-01T00:00:00.000+02:00
42,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_5,T3_TipoDato,Provisional
43,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_5,T3_Periodo,M07
44,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_5,Anyo,2024
45,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_5,Valor,85.38
46,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_6,Fecha,2024-06-01T00:00:00.000+02:00
47,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_6,T3_TipoDato,Provisional
48,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_6,T3_Periodo,M06
49,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_6,Anyo,2024
50,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_6,Valor,74.72
51,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_7,Fecha,2024-05-01T00:00:00.000+02:00
52,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_7,T3_TipoDato,Provisional
53,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_7,T3_Periodo,M05
54,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_7,Anyo,2024
55,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_7,Valor,72.59
56,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_8,Fecha,2024-04-01T00:00:00.000+02:00
57,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_8,T3_TipoDato,Provisional
58,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_8,T3_Periodo,M04
59,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_8,Anyo,2024
60,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_8,Valor,66.0
61,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_9,Fecha,2024-03-01T00:00:00.000+01:00
62,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_9,T3_TipoDato,Provisional
63,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_9,T3_Periodo,M03
64,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_9,Anyo,2024
65,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_9,Valor,65.53
66,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_10,Fecha,2024-02-01T00:00:00.000+01:00
67,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_10,T3_TipoDato,Provisional
68,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_10,T3_Periodo,M02
69,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_10,Anyo,2024
70,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_10,Valor,63.27
71,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_11,Fecha,2024-01-01T00:00:00.000+01:00
72,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_11,T3_TipoDato,Provisional
73,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_11,T3_Periodo,M01
74,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_11,Anyo,2024
75,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_11,Valor,60.19
76,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_12,Fecha,2023-12-01T00:00:00.000+01:00
77,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_12,T3_TipoDato,Definitivo
78,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_12,T3_Periodo,M12
79,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_12,Anyo,2023
80,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_12,Valor,65.52
81,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_13,Fecha,2023-11-01T00:00:00.000+01:00
82,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_13,T3_TipoDato,Definitivo
83,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_13,T3_Periodo,M11
84,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_13,Anyo,2023
85,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_13,Valor,63.26
86,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_14,Fecha,2023-10-01T00:00:00.000+02:00
87,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_14,T3_TipoDato,Definitivo
88,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_14,T3_Periodo,M10
89,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_14,Anyo,2023
90,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_14,Valor,67.36
91,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_15,Fecha,2023-09-01T00:00:00.000+02:00
92,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_15,T3_TipoDato,Definitivo
93,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_15,T3_Periodo,M09
94,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_15,Anyo,2023
95,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_15,Valor,71.06
96,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_16,Fecha,2023-08-01T00:00:00.000+02:00
97,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_16,T3_TipoDato,Definitivo
98,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_16,T3_Periodo,M08
99,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_16,Anyo,2023
100,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_16,Valor,84.46
101,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_17,Fecha,2023-07-01T00:00:00.000+02:00
102,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_17,T3_TipoDato,Definitivo
103,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_17,T3_Periodo,M07
104,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_17,Anyo,2023
105,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_17,Valor,83.53
106,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_18,Fecha,2023-06-01T00:00:00.000+02:00
107,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_18,T3_TipoDato,Definitivo
108,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_18,T3_Periodo,M06
109,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_18,Anyo,2023
110,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_18,Valor,76.89
111,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_19,Fecha,2023-05-01T00:00:00.000+02:00
112,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_19,T3_TipoDato,Definitivo
113,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_19,T3_Periodo,M05
114,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_19,Anyo,2023
115,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_19,Valor,67.16
116,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_20,Fecha,2023-04-01T00:00:00.000+02:00
117,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_20,T3_TipoDato,Definitivo
118,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_20,T3_Periodo,M04
119,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_20,Anyo,2023
120,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_20,Valor,67.1
121,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_21,Fecha,2023-03-01T00:00:00.000+01:00
122,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_21,T3_TipoDato,Definitivo
123,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_21,T3_Periodo,M03
124,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_21,Anyo,2023
125,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_21,Valor,60.54
126,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_22,Fecha,2023-02-01T00:00:00.000+01:00
127,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_22,T3_TipoDato,Definitivo
128,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_22,T3_Periodo,M02
129,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_22,Anyo,2023
130,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_22,Valor,58.29
131,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_23,Fecha,2023-01-01T00:00:00.000+01:00
132,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_23,T3_TipoDato,Definitivo
133,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_23,T3_Periodo,M01
134,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_23,Anyo,2023
135,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_23,Valor,56.18
136,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_24,Fecha,2022-12-01T00:00:00.000+01:00
137,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_24,T3_TipoDato,Definitivo
138,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_24,T3_Periodo,M12
139,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_24,Anyo,2022
140,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_24,Valor,60.43
141,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_25,Fecha,2022-11-01T00:00:00.000+01:00
142,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_25,T3_TipoDato,Definitivo
143,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_25,T3_Periodo,M11
144,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_25,Anyo,2022
145,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_25,Valor,59.11
146,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_26,Fecha,2022-10-01T00:00:00.000+02:00
147,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_26,T3_TipoDato,Definitivo
148,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_26,T3_Periodo,M10
149,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_26,Anyo,2022
150,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_26,Valor,67.2
151,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_27,Fecha,2022-09-01T00:00:00.000+02:00
152,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_27,T3_TipoDato,Definitivo
153,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_27,T3_Periodo,M09
154,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_27,Anyo,2022
155,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_27,Valor,68.72
156,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_28,Fecha,2022-08-01T00:00:00.000+02:00
157,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_28,T3_TipoDato,Definitivo
158,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_28,T3_Periodo,M08
159,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_28,Anyo,2022
160,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_28,Valor,81.55
161,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_29,Fecha,2022-07-01T00:00:00.000+02:00
162,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_29,T3_TipoDato,Definitivo
163,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_29,T3_Periodo,M07
164,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_29,Anyo,2022
165,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_29,Valor,78.09
166,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_30,Fecha,2022-06-01T00:00:00.000+02:00
167,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_30,T3_TipoDato,Definitivo
168,EOT43602,Vitoria-Gasteiz. Tarifa media diaria (ADR). Total categorías. Dato base.,Data,Item_30,T3_Periodo,M06

In [10]:
pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.2.0-cp310-cp310-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.2.0-cp310-cp310-win_amd64.whl (68 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.2.0
Note: you may need to restart the kernel to use updated packages.

In [12]:
import pyodbc

# Configuración de la conexión
conexion = pyodbc.connect(
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=localhost;'
    'DATABASE=staging;'
    'UID=AbolrousHazem;'
    'PWD=340$Uuxwp7Mcxo7Khy'
)

cursor = conexion.cursor()

In [ ]:
pip install sqlalchemy

In [15]:
import pandas as pd
from sqlalchemy import create_engine

# Configuración de conexión a SQL Server
engine = create_engine(
    "mssql+pyodbc://AbolrousHazem:340$Uuxwp7Mcxo7Khy@localhost/staging?driver=ODBC+Driver+17+for+SQL+Server"
)